{% set name = "pyincore-incubator" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

about:
  home: https://incore.ncsa.illinois.edu
  license: MPL-2.0
  summary: 'Python library for IN-CORE (Interdependent Networked Community Resilience Modeling Environment)'
  description: 'pyIncore-incubator is a component of IN-CORE that allows users to extend
  the core set of analyses provided by pyIncore. New analyses in pyincore-incubator
  extend the pyincore BaseAnalysis class and can be chained with existing pyincore
  analyses to add new functionality. The incubator gives the community around the
  IN-CORE project a forum and set of resources for innovation and investigation of new
  ideas and alternative ideas.'
  dev_url: https://github.com/IN-CORE/pyincore-incubator
  doc_url: https://incore.ncsa.illinois.edu/doc/incore

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  #number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv . " # verbose
 
requirements:
  build:
    - python>=3.9
    - pip
    - numpy>=1.26.0,<2.0a0
 
  host:
    - python>=3.9
    - pip
    - numpy>=1.26.0,<2.0a0

  run:
    - python>=3.9
    - scip>=8.0.0
    - {{ pin_compatible('numpy') }}
    - fiona>=1.9.5
    - geopandas>=0.14.0
    - matplotlib>=3.8.0
    - networkx>=3.2.1
    - pandas>=2.1.2
    - pyincore
    - pyomo>=6.6.2
    - pyproj>=3.6.1
    - rasterio>=1.3.9
    - requests>=2.31.0
    - rtree>=1.1.0
    - scipy>=1.11.3
    - shapely>=2.0.2

test:
  # Python imports
  imports:
    - pyincore_incubator
   
  requires:
    # Put any additional test requirements here.  For example
    - pytest>=3.9.0
    - pycodestyle>=2.6.0
    - python-jose>=3.0

  commands:
    # You can put built-in test commands to be run here.  Use this to test that the entry points work.
    python -c "import pyincore_incubator; print('SUCCESS')" #; pyincore.test_client()"
    # You can also put a file called run_test.py in the recipe that will be run at test time.
